### ISSUE TITLE
Make labels more human-friendly

### ISSUE THREAD

**Issue by jdm** [servo/servo-starters#1]
They're currently designed for power users and ordering concerns. We can do translations like this:
- A-foo => "area: foo"
- E-easy => "good first PR" (maybe even put a friendly star next to the issue)
- E-less-easy => "mentored"
- L-foo => "language: foo"
- B-foo-bar => "foo bar"
- S-foo-bar => "status: foo bar"
- I-foo => "category: foo" (not thrilled with this one; we may want to just ignore I- labels)
- C-foo-bar => "status: foo bar" (whee organizational duplication)
- P-foo => "platform: foo"

**Comment by metajack** [comment]
+1 in general. Some specific suggestions:
- we should cull many of the labels in general instead of keeping them and renaming
- make the labels have no spaces after `:`. like `area:foo`.
- the only useful B- label in my opinion is B-meta, but agreed it should just be meta. remove the rest.
- For L- I suggest `lang:foo`
- There seem to be two classes of C- labels. The first is closed reasons, which I think should be `closed:$reason`. The second is status of which the only really useful one is assigned. Maybe delete the rest and make C-assigned part of status `status:assigned`.
- For I-, I'd cull a lot of these, and just do `type:$type` and keep mainly things like type:crash, type:leak etc.

**Comment by mfeckie** [comment]
@jdm Can this be closed now?

**Comment by jdm** [comment]
Yes!
